# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-14 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adapter', '0002_auto_20170113_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminaccount',
            name='interface',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
